# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Armada' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Armada

  target 'Armada-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ArmadaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Armada-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Armada-tvOS

  target 'Armada-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
